# Generated by Django 4.0.1 on 2022-02-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cartorder_cartorderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='order',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mobilebrand',
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
        migrations.DeleteModel(
            name='CartOrderItems',
        ),
        migrations.DeleteModel(
            name='mobilebrand',
        ),
    ]
