# Generated by Django 4.0.1 on 2022-04-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mod',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
